### ISSUE TITLE
Check and merge forked code

### ISSUE THREAD

**Issue by humbertobz** [jlherren/skype-call-recorder#1]
Check fork[1] and merge code to this main repository.

[1] https://github.com/proton/SkypeRec

**Comment by jlherren** [comment]
That fork is of poor quality.

The commits are poorly documented and full of spelling mistakes. Many commits are essentially just about rebranding the entire thing. Many other commits are about questionable refactoring (some even introduce bugs). The only interesting thing I could find was the Russian translation.
