### ISSUE TITLE
skype 4.3 and allow skype call recorder problem

### ISSUE THREAD

**Issue by sates52** [jlherren/skype-call-recorder#4]
We are using skype 4.3 on lubuntu 14.04

After we run skype call recorder it asks to allow skype call recorder to skype. We check remember section but it doesnt remember. Before each call it asks again and again. Any update or solution for that?

![2014-08-21-062218_1366x768_scrot](https://cloud.githubusercontent.com/assets/8513430/3995979/39d1ee04-292f-11e4-9c48-a0e6f24ad37c.png)

**Comment by jlherren** [comment]
I couldn't reproduce this on Ubuntu 14.04. I assume it's essentially similar to Lubuntu 14.04. However since this dialog is from Skype and not SCR, there's a chance this is a bug in Skype.
