### ISSUE TITLE
Allow to disable the legal warning and the tray icon

### ISSUE THREAD

**Issue by etlel** [jlherren/skype-call-recorder#8]
I'd add the possibility to stop to visualize the legal warning once readed (something like « do not show anymore »), and also a configuration option to disable the tray icon.

Thank you for this good flexible tool.

**Comment by jlherren** [comment]
There's already a checkbox to not show the legal warning anymore, but you have to click "Show more information" first to see it.

And how would disabling the try icon work? That's where you access all the features. How would you open the settings without the icon? Or exit the program?
